trigger:
  branches:
    include:
    - main
    - master

pool: 
  name: Umesh  # Uses the self-hosted 'Default' pool


# Checkmarx SCA
steps:
- task: checkmarx.cxsast.cx-scan-task.Application security testing@2025
  displayName: Umesh
  inputs:
    projectName: 'SharedServices-ENext-Filer-Management'
    enableProxy: false
    enableSastScan: false
    enableDependencyScan: true
    dependencyServerURL: 'SCA'
    scaTeam: '/CxServer'